
development:
  adapter: postgresql
  encoding: unicode
  database: admi_facile_development
  host: localhost
  pool: 5
  username: admi_facile
  password: lol


test:
  adapter: postgresql
  encoding: unicode
  database: admi_facile_test
  host: localhost
  pool: 5
  username: admi_facile
  password: lol


