development:
  adapter: postgresql
  encoding: unicode
  database: tps_development
  host: localhost
  pool: 5
  username: tps
  password: lol


test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
