default:
  openstack_tenant: "ovh_fake_tenant_name"
  openstack_api_key: "ovh_fake_password"
  openstack_username: "ovh_fake_username"
  openstack_auth_url: "https://auth.cloud.ovh.net/v2.0/tokens"
  openstack_region: "SBG1"
